
name: Deploy to Firebase Hosting

# This workflow deploys the static-generated nextjs app to Firebase Hosting
# Triggered by push to the "dev" branch
on:
  push:
    branches:
      - dev
      - feature/weaponsforge-48

jobs:
  lint-export-client:
    name: Lint and Export client
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: ''
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use NodeJS v16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Install Dependencies and lint
        run: |
          cd client
          npm install
      - name: Lint
        run: |
          cd client
          npm run lint
      - name: Export static files
        run: |
          cd client
          npm run export
      - name: Archive Development Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dev-app
          path: |
            client/out
            client/firebase.json
            client/.firebaserc
          retention-days: 3

  deploy-client:
    name: Deploy Client to Firebase Hosting
    needs: lint-export-client
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dev-app
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
